def build_sql_prompt(execution_plan_json: str) -> str:
    """
    Enterprise Semantic Prompt Builder.
    Receives a strict, deterministic Execution Plan generated by the Query Planner.
    The LLM's only job is to translate this exact plan into MySQL syntax.
    """
    prompt = f"""You are an Enterprise AI Data Analyst for this company.
Your job is to generate an optimized read-only MySQL query strictly based on the Execution Plan provided below.

EXECUTION PLAN:
{execution_plan_json}

RULES:
1. NEVER guess or hallucinate tables, columns, or relationships. Use ONLY the tables and schema details provided in the Execution Plan.
2. ALWAYS use explicit columns. NEVER use SELECT *.
3. PAY ATTENTION to the Data Types and ENUM values provided in the schema_details. Do not compare integers to strings, or guess enum values that aren't listed.
4. ALWAYS use table aliases (e.g., `FROM users u JOIN roles r ON u.role_id = r.id`).
5. ALWAYS apply LIMIT 500 unless specifically computing an aggregate value (COUNT, SUM, MAX).
6. IF the plan provides Business Terms, map them correctly to the table values.
7. YOU MUST OUTPUT A STRUCTURED RESPONSE EXACTLY LIKE THIS:

PLAN:
Intent: [What the business user is asking]
Output: [What the output represents]
---
SQL:
SELECT ...

Generate the response now:"""

    return prompt.strip()
